spring:
  application:
    name: process_payments

zeebe:
  client:
    broker:
      gateway-address: http://127.0.0.1:26500
      grpcAddress: http://127.0.0.1:26500
      restAddress: http://127.0.0.1:8080
    security:
      plaintext: true

camunda:
  operate:
  client:
    url: http://localhost:8081
    username: demo
    password: demo
